name: Sync with Upstream

on:
  push:
  schedule:
    - cron: '0 0 * * *' # Run the workflow daily

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your.email@example.com'

      - name: Fetch upstream changes
        run: |
            git remote add upstream https://github.com/mrrfv/cloudflare-gateway-pihole-scripts.git
            git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main

      - name: Push changes to fork
        run: git push origin main
