name: Sync with Upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git config
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Fetch upstream changes
        run: |
          git remote add upstream https://github.com/mrrfv/cloudflare-gateway-pihole-scripts.git
          git fetch upstream

      - name: Set modified files
        id: set-modified-files
        run: echo "::set-output name=MODIFIED_FILES::$(git diff --name-only upstream/main)"

      - name: Merge upstream changes
        run: git merge --allow-unrelated-histories upstream/main

      - name: Push changes to fork
        run: git push origin main

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Sync with upstream"
          title: "Sync with upstream"
          body: "Changes: ${{ steps.set-modified-files.outputs.MODIFIED_FILES }}"