name: Sync with Upstream

on:
  push:
  schedule:
    - cron: '0 0 * * *' # Run the workflow daily

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your.email@example.com'

      - name: Fetch upstream changes
        run: |
          git remote add upstream https://github.com/mrrfv/cloudflare-gateway-pihole-scripts.git
          git fetch upstream
          git checkout -b temp-branch upstream/main
          git checkout main
          git merge --allow-unrelated-histories --no-edit temp-branch
          git branch -D temp-branch

      - name: Check for new files
        id: new_files
        run: |
          git diff --name-only --diff-filter=A upstream/main > new_files.txt
          if [ -s new_files.txt ]; then
            echo "New files found. Creating pull requests..."
          else
            echo "No new files found."
            exit 0
          fi

      - name: Create pull requests
        run: |
          while IFS= read -r file; do
            echo "Creating pull request for $file..."
            branch_name="feature-branch-$file"

            # Checkout a new branch
            git checkout -b "$branch_name"

            # Attempt to add and commit the file
            if git add "$file" && git commit -m "Sync with upstream - $file"; then
              # Push the branch to origin
              git push origin "$branch_name"

              # Create a pull request
              hub pull-request -m "Sync with upstream - $file" -b main -h "$branch_name"
            else
              # If there are conflicts, skip this file and print a message
              echo "Merge conflict in $file. Skipping..."
              git reset --hard HEAD
            fi
          done < new_files.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
