name: Sync with Upstream

on:
  push:
  schedule:
    - cron: '0 0 * * *' # Run the workflow daily

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your.email@example.com'

      - name: Fetch upstream changes
        run: |
          git remote add upstream https://github.com/mrrfv/cloudflare-gateway-pihole-scripts.git
          git fetch upstream
          git merge --allow-unrelated-histories upstream/main

      - name: Check for new files
        id: new_files
        run: |
          git diff --name-only --diff-filter=A upstream/main > new_files.txt
          if [ -s new_files.txt ]; then
            echo "New files found. Creating pull request..."
          else
            echo "No new files found."
            exit 0
          fi

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: feature-branch
          title: Sync with upstream
          base: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
