name: Sync with Upstream

on:
  push:
  schedule:
    - cron: '0 0 * * *' # Run the workflow daily

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your.email@example.com'

      - name: Fetch upstream changes
        run: |
          git remote add upstream https://github.com/mrrfv/cloudflare-gateway-pihole-scripts.git
          git fetch upstream

      - name: Check if feature-branch exists and delete it
        run: |
          if git show-ref --quiet refs/heads/feature-branch; then
            git branch -D feature-branch
          fi

      - name: Create a new branch for changes
        run: git checkout -b feature-branch

      - name: Merge upstream changes
        run: git merge --allow-unrelated-histories upstream/main

      - name: Push changes to fork
        run: |
          git pull origin feature-branch
          git push origin feature-branch

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: feature-branch
          title: Sync with upstream
          base: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
