name: Sync with Upstream

on:
  push:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

    - name: Fetch upstream
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git remote add upstream https://github.com/mrrfv/cloudflare-gateway-pihole-scripts.git
        git fetch upstream

    - name: Rebase changes
      run: |
        git fetch origin main
        git merge origin/main
        git rebase -Xtheirs upstream/main

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        branch: ${{ github.ref }}
        force: true