name: Create and Merge Branch

on:
  workflow_dispatch:
    inputs:
      force_merge:
        description: 'Force merge branch to main'
        required: false
        default: 'false'

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your.email@example.com'

      - name: Create Original Branch
        run: |
          git checkout -b original
          git push -u origin original

  merge-upstream:
    runs-on: ubuntu-latest
    needs: [create-branch]
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set Git User
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Fetch Upstream Changes
        run: |
          git remote add upstream https://github.com/mrrfv/cloudflare-gateway-pihole-scripts.git
          git fetch upstream
          git rebase upstream/main || git rebase --abort

      - name: Push Merged Branch to Main
        run: |
          # Choose whether to force push or not
          if ${{ github.event.inputs.force_merge }} == 'true'; then
            git push origin main --force
          else
            git push origin main
          fi

